version: '3'

services:
  database:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sf_db
      MYSQL_USER: sf_user
      MYSQL_PASSWORD: sf_pass
    volumes:
      - ./../sf_db:/var/lib/mysql
    restart: on-failure

  server:
    image: nginx:1.23.3-alpine
    ports:
      - "8090:80"
    restart: always
    volumes:
      - './:/usr/src/app'
      - './.docker/server/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: ./.docker/app/DockerFile
    volumes:
      - './:/usr/src/app'
    restart: on-failure
    env_file:
      - .env
    user: 1000:1000

